module.exports = {
  content: [
    'src/pages/**/*.{js,ts,jsx,tsx}',
    'src/components/**/*.{js,ts,jsx,tsx}',
  ],
  darkMode: 'class',
  theme: {
    screens: {
      md: '768px',
      lg: '1056px',
      xl: '1440px',
      '2xl': '1920px',
    },
    extend: {
      typography: ({ theme }) => ({
        zinc: {
          css: {
            '--tw-prose-body': theme('colors.zinc[800]'),
            '--tw-prose-headings': theme('colors.zinc[800]'),
            '--tw-prose-lead': theme('colors.zinc[800]'),
            '--tw-prose-links': theme('colors.teal[600]'),
            '--tw-prose-bold': theme('colors.pink[600]'),
            '--tw-prose-counters': theme('colors.zinc[800]'),
            '--tw-prose-bullets': theme('colors.zinc[800]'),
            '--tw-prose-hr': theme('colors.zinc[800]'),
            '--tw-prose-quotes': theme('colors.zinc[800]'),
            '--tw-prose-quote-borders': theme('colors.zinc[800]'),
            '--tw-prose-captions': theme('colors.zinc[800]'),
            '--tw-prose-code': theme('colors.amber[50]'),
            '--tw-prose-pre-code': theme('colors.zinc[800]'),
            '--tw-prose-pre-bg': theme('colors.zinc[800]'),
            '--tw-prose-th-borders': theme('colors.zinc[800]'),
            '--tw-prose-td-borders': theme('colors.zinc[800]'),
            // dark-mode
            '--tw-prose-invert-body': theme('colors.amber[50]'),
            '--tw-prose-invert-headings': theme('colors.amber[50]'),
            '--tw-prose-invert-lead': theme('colors.amber[50]'),
            '--tw-prose-invert-links': theme('colors.teal[400]'),
            '--tw-prose-invert-bold': theme('colors.pink[400]'),
            '--tw-prose-invert-counters': theme('colors.amber[50]'),
            '--tw-prose-invert-bullets': theme('colors.amber[50]'),
            '--tw-prose-invert-hr': theme('colors.amber[50]'),
            '--tw-prose-invert-quotes': theme('colors.amber[50]'),
            '--tw-prose-invert-quote-borders': theme('colors.amber[50]'),
            '--tw-prose-invert-captions': theme('colors.amber[50]'),
            '--tw-prose-invert-code': theme('colors.amber[50]'),
            '--tw-prose-invert-pre-code': theme('colors.amber[50]'),
            '--tw-prose-invert-pre-bg': theme('colors.gray[900]'),
            '--tw-prose-invert-th-borders': theme('colors.amber[50]'),
            '--tw-prose-invert-td-borders': theme('colors.amber[50]'),
          },
        },
      }),
    },
  },
  plugins: [
    require('tailwind-scrollbar-hide'),
    require('@tailwindcss/typography'),
  ],
};
